language: python
python:
  - { PATH: "{{replace(Python34, '\\', '\\\\')}}", VERSION: 3.4, DIST: std }
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Python27, '\\', '\\\\')}}", VERSION: 2.7, DIST: std }
  - { PATH: "{{replace(Anaconda3, '\\', '\\\\')}}", VERSION: 3.5, DIST: conda }
  - { PATH: "{{replace(Anaconda2, '\\', '\\\\')}}", VERSION: 2.7, DIST: conda }
  - { PATH: "{{replace(WinPython35, '\\', '\\\\')}}", VERSION: 3.5, DIST: winpython }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
install:
  - pip install --no-cache-dir --index http://localhost:8067/simple/ pyquickhelper
  - pip install -r requirements.txt
  - pip freeze
before_script:
  - if [ ${VERSION} == "2.7" ] then {{Python35}}\python setup.py copy27 fi
  - if [ ${VERSION} == "2.7" ] then cd dist_module27 fi
script:
  - { CMD: "python setup.py unittests", NAME: "UT" }
after_script:
  - python setup.py bdist_wheel
  - if [ ${VERSION} == "2.7" and ${DIST} != "conda" ] then copy dist\*.whl ..\..\..\local_pypi\local_pypi_server fi
  - if [ ${VERSION} == "2.7" ] then cd .. fi
  - if [ ${VERSION} != "2.7" and ${DIST} != "conda" and ${VERSION} != "3.4" ] then copy dist\*.whl ..\..\local_pypi\local_pypi_server fi
documentation:
  - if [ ${PYTHON} == "{{Python35}}" ] then python setup.py build_sphinx fi
  - if [ ${PYTHON} == "{{Python35}}" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
  - if [ ${PYTHON} == "{{Python35}}" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\epub dist\epub fi
  - if [ ${PYTHON} == "{{Python35}}" ] then copy _doc\sphinxdoc\build\htmlhelp\*.chm dist\html fi
  - if [ ${PYTHON} == "{{Python35}}" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\latex\*.pdf dist\html fi
