language: python
python:
  - { PATH: "{{replace(Python34, '\\', '\\\\')}}", VERSION: 3.4, DIST: std }
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Python27, '\\', '\\\\')}}", VERSION: 2.7, DIST: std }
  - { PATH: "{{replace(Anaconda3, '\\', '\\\\')}}", VERSION: 3.5, DIST: conda }
  - { PATH: "{{replace(Anaconda2, '\\', '\\\\')}}", VERSION: 2.7, DIST: conda }
  - { PATH: "{{replace(WinPython35, '\\', '\\\\')}}", VERSION: 3.5, DIST: winpython }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
install:
  - pip install --no-cache-dir --index http://localhost:8067/simple/ pyquickhelper
  - pip install -r requirements.txt
  - pip freeze
before_script:
  - if [ ${VERSION} == "2.7" ] then python setup.py copy27 fi
  - if [ ${VERSION} == "2.7" ] then cd dist_module27 fi
script:
  - { CMD: "python setup.py unittests", NAME: "UT" }
after_script:
  - python setup.py bdist_wheel
  - if [ ${VERSION} == "2.7" ] copy dist\*.whl ..\..\..\local_pypi\local_pypi_server
  - if [ ${VERSION} == "2.7" ] then cd .. fi
  - if [ ${VERSION} != "2.7" ] copy dist\*.whl ..\..\local_pypi\local_pypi_server
documentation:
  - if [ ${PYTHON} == "{{Python35}}" ] then
    python setup.py build_sphinx
    fi
