language: python
python:
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Python36, '\\', '\\\\')}}", VERSION: 3.6, DIST: std }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
install:
  - pip freeze
  - pip freeze > pip_freeze.txt
  - mkdir dist
script:
  - { CMD: "whl\\windows\\build___MODULE__.bat ${Python}", NAME: "__MODULE__" }
after_script:
  - copy dist\*.whl ..

